INSERT INTO pets (pet_name, sex, age, size, animal, contact, breeds, media, description)

VALUES 
('Phefee', "f", 21, "small", "dog", "RCB Pet Shelter (908)-867-5309", 'Schnauzer', "http://royal-schnauzers.com/images/Lilly%202-9-08.JPG", "Phefee is a friend to all! She is currently owned by Bill Moffa, but he wants you to get her highness out of his house and take her home with you today!"),
('Xavier', "m", 3, "medium", "cat", "RCB Pet Shelter (908)-867-5309", 'Tabby', "https://fthmb.tqn.com/2c7xClaayuwi0bMtzhWgqG2_Bgw=/2117x1417/filters:no_upscale():fill(transparent,1)/about/103759666-56a111c43df78cafdaa916d7.jpg", "Xavier has had issues with certain humans, but we think that the right one will change his outlook on people. Adopt him today!" ),
('Buttons', "m", 20, "large", "dog", "RCB Pet Shelter (908)-867-5309", 'Loyal Friend', "https://s-media-cache-ak0.pinimg.com/736x/74/b5/b4/74b5b487206ed49ea809fa8c92a53ea2.jpg", "Buttons is Mindy's faithful dog who appeared on Animaniacs. Buttons is a lot like Lassie but gets in trouble instead of being the hero. He is often harmed by whatever danger Mindy narrowly avoids. He has a tendency to scream like a chicken and a monkey at times. Buttons enjoys Mindy's company and loves her dearly. He looks out for her when she runs off and will do anything to help her and get her back." ),
('Brian', "m", 8, "medium", "dog", "RCB Pet Shelter (908)-867-5309", 'Labrador', "http://www.caninest.com/images/brian.jpg", "Brian Griffin has lived with the Griffin family since Peter picked him up as a stray. He also possesses various anthropomorphic qualities, such as the ability to speak intelligently, drive a car, and walk bipedally." ),
('Sam', "f", 4, "small", "dog", "RCB Pet Shelter (908)-867-5309", 'Ugly Dog', "https://upload.wikimedia.org/wikipedia/en/d/df/Sam_dog.jpg", "Sam has had the more unfortunate life than most living animals today. She routinely breaks mirrors and her presence alone will clear a crowded room. She's a perfect choice for an introvert who also hates mirrors."),
('Sasha', "f", 1, "small", "dog", "RCB Pet Shelter (908)-867-5309", 'Short Hair Domestic', "https://img.buzzfeed.com/buzzfeed-static/static/2015-06/24/19/campaign_images/webdr09/this-may-be-this-cutest-saddest-cat-ever-2-4626-1435188004-0_dblbig.jpg", "Sahsha is ready for someone to love her more than they love themselves. Her eyes will peer into your soul. Adopt this huggable, loveable cat today!"),
('Scooby Doo', "m", 48, "large", "dog", "RCB Pet Shelter (908)-867-5309", 'Great Dane', "https://pmcvariety.files.wordpress.com/2015/08/scooby-doo-warner-bros.jpg?w=670&h=377&crop=1", "Scoobert 'Scooby' Doo is the eponymous character and protagonist of the animated television franchise of the same name created in 1969 by the American animation company Hanna-Barbera. Scooby-Doo is a male Great Dane and lifelong companion of amateur detective Shaggy Rogers, with whom he shares many personality traits. Named after a nonsense vocal line in Frank Sinatra's hit song 'Strangers in the Night', he features a mix of both canine and human behaviors (reminiscent of other funny animals in the Golden age of American animation), treated by his friends more or less as an equal while speaking in a famous (and much parodied) speech impediment. His catchphrase is Scooby-Dooby-Doo!"),
('Loki', "m", 2, "large", "dog", "RCB Pet Shelter (908)-867-5309", 'Wolf Dog', "http://images1.westword.com/imager/u/original/8168687/photo_oct_18_9_14_55_am.jpg", "Loki is orignally from Denver, but somehow we ended up with him. We would rather not give him up, but if you really feel like you need to adopt him then come by today and we'll see if you're worthy."),
('Garfield', "m", 30, "medium", "cat", "RCB Pet Shelter (908)-867-5309", 'Exotic Shorthair', "https://s-media-cache-ak0.pinimg.com/736x/69/38/82/6938826f0421d67dd82b8c67f99336a4.jpg", "Garfield is a fictional character and the titlular protagonist from the comic strip Garfield created by Jim Davis. The comic strip centers on Garfield, portrayed as a lazy, fat, and cynical orange cat with the ability to speak articulately. He is noted for his love of lasagna, coffee and sleeping, and his hatred of Mondays, fellow cat Nermal (sometimes), raisins and exercise."),
('Sylvester',"m", 72, "large", "cat", "RCB Pet Shelter (908)-867-5309", 'Puddy Tat', "http://e.snmc.io/lk/f/s/f852f34c0c35f4efa50c0d2f774f6cfb/4298043.jpg", "Sylvester J. Pussycat, Sr., Sylvester the Cat or simply Sylvester, or Puddy Tat, is a fictional character, a three-time Academy Award-winning anthropomorphic Tuxedo cat in the Looney Tunes and Merrie Melodies repertory, often chasing Tweety Bird, Speedy Gonzales, or Hippety Hopper. The name 'Sylvester' is a play on Felis silvestris, the scientific name for the wild cat species (domestic cats like Sylvester, though, are actually Felis catus)." );